### ISSUE TITLE
Плагин не работает на 1.20.2

### ISSUE THREAD

**Issue by nikolayvsks** [IEnumerablee/Volleyball#10]
При попытке создать мяч на версии 1.20.2 (paper-280) плагин выдаёт ошибку:
```
[Server thread/ERROR]: Could not pass event PlayerInteractEvent to Volleyball v1.4
java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at ru.ienumerable.volleyball.skin.SkullSkin.getSkullByUrl(SkullSkin.java:86) ~[Volleyball-1.4.jar:?]
	at ru.ienumerable.volleyball.skin.SkullSkin.getItem(SkullSkin.java:43) ~[Volleyball-1.4.jar:?]
	at ru.ienumerable.volleyball.ball.Ball.spawnStand(Ball.java:264) ~[Volleyball-1.4.jar:?]
	at ru.ienumerable.volleyball.ball.Ball.<init>(Ball.java:45) ~[Volleyball-1.4.jar:?]
	at ru.ienumerable.volleyball.ThrowController.throwBall(ThrowController.java:35) ~[Volleyball-1.4.jar:?]
	at ru.ienumerable.volleyball.EventListener.craftBall(EventListener.java:85) ~[Volleyball-1.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-290]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-290]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-290]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595) ~[paper-1.20.2.jar:git-Paper-290]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:552) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1973) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-290]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by ComboGame** [comment]
ну кекич

**Comment by StelStelox** [comment]
Хз на 1.20.4 всё стабильно. Попробуй запустить плагин на другом ядре без других плагинов

**Comment by MrSculk1945** [comment]
> Хз на 1.20.4 всё стабильно. Попробуй запустить плагин на другом ядре без других плагинов

Блиин, как ты так сделал? у меня просто появляеться обычный армор стенд... Подскажи свое ядро пожалуйста
